DROP TRIGGER update_candidate_timestamp ON candidates;
DROP TRIGGER update_citizen_timestamp ON citizens;
DROP TABLE beta_codes;
DROP TABLE waiting_list;
DROP TABLE conversations;
DROP TABLE reviews;
DROP TABLE humanbots;
DROP TABLE reviewers;
DROP TABLE donations;
DROP TABLE supporters;
DROP TABLE candidates_views;
DROP TABLE candidates;
DROP TABLE citizens_tags;
DROP TABLE tags;
DROP TABLE citizens;
DROP TABLE cities;
DROP TABLE countries;
